# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'armDeployNew'
    subscriptionId: '485d828b-d283-4732-bbe5-dbbcee12efe1'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'armTemplateRG1'
    location: 'UK South'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    csmParametersFile: 'CreateWebApp/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'armautodeploy'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
